version: '3'
services:
  web:
    image: node:20-alpine
    ports:
      - 3000:5173
    volumes:
      - ./web:/web
    working_dir: /web
    entrypoint: npm run dev
    depends_on:
      - server

  server:
    image: node:20-alpine
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
    working_dir: /server
    entrypoint: npm run dev
